swagger: '2.0'
info:
  version: 1.0.0
  title: Hello World API
schemes:
  - https
host: localhost
basePath: /api
paths:
  /hello-world:
    get:
      summary: Hello World
      responses:
        '200':
          description: Successful invokation

